Consistent avatar colors
session-foundation/session-appium pull request #13
Opened 2024-11-18 04:59 UTC by Miki-Session

- new `colorCompare` utility allows color comparisons within a "humans-can't-tell-the-difference" tolerance
- new test specs for verifying consistent placeholder avatar colors 
    - a user's color is the same on their own device and a contact's device
    - a user's color is the same across their own linked devices

2024-11-18 05:04 UTC, Miki-Session commented
looks like eslint failing is a known issue
https://github.com/eslint/eslint/issues/19134

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/utils/check_colour.ts
> +  }
that whole function should be moved outside of `compareColors`

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/utils/check_colour.ts
> +    const bigint = parseInt(hex.replace('#', ''), 16);
[BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) is a reserved keyword in JS. It's a bit weird to name something that close. Maybe rename it to `asInt` or something else?

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/utils/check_colour.ts
> +  tolerance: number = 2.3 // looks-same default value which is "enough for most cases"
don't duplicate values that don't need to be.
If `looks-same` changes their default in another release, we will be stuck with that one. I assume we don't want to, so make `tolerance ?: number` and deal with the type issues below by checking if tolerance is defined or not.
Or remove tolerance altogether as we don't seem to be using it.

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/linked_device_avatar_color.spec.ts
> +  if (!colorCompare) {
a bit of a weird name as it is a boolean. Maybe name it something that matches better, like `colorMatch` or `closeEnough`

"compare" in IT kind of sounds like it's returning -1, 0 or 1, depending on if the color is smaller, the same or bigger (whatever that'd mean for colors :joy: )

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/linked_device_avatar_color.spec.ts
> +  }
no need for an else after a throw

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/utils/check_colour.ts
> +): boolean {
no need to type this, the type is inferred correctly from the return, and this just becomes one more type to maintain, long term

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/check_avatar_color.spec.ts
> +  if (!colorCompare) {
better name for variable, see below

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/check_avatar_color.spec.ts
> +    );
no else after throw, see below

2024-12-16 06:52 UTC, Bilb commented on package.json
> +    "looks-same": "^9.0.1",
for what we use that package and what it can do, we should probably write the looks-same for colors ourselves, but I'll let you do what you want.

2024-12-16 06:52 UTC, Bilb commented on run/test/specs/linked_device_avatar_color.spec.ts
> +  if (!colorCompare) {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#comparefn

2025-01-08 05:04 UTC, Miki-Session commented on package.json
> +    "looks-same": "^9.0.1",
I do intend to use more of the package in future tests (e.g., QA-306)

2025-01-08 05:05 UTC, Miki-Session commented on run/test/specs/utils/check_colour.ts
> +  }
now part of utilities.ts

2025-01-08 05:05 UTC, Miki-Session commented on run/test/specs/utils/check_colour.ts
> +    const bigint = parseInt(hex.replace('#', ''), 16);
went with `decimalValue` in the end

2025-01-08 05:06 UTC, Miki-Session commented on run/test/specs/linked_device_avatar_color.spec.ts
> +  if (!colorCompare) {
insightful, went with `colorMatch` in both instances

2025-01-08 05:07 UTC, Miki-Session commented on run/test/specs/utils/check_colour.ts
> +  tolerance: number = 2.3 // looks-same default value which is "enough for most cases"
got rid of the tolerance value altogether

2025-01-08 05:07 UTC, Miki-Session commented on run/test/specs/utils/check_colour.ts
> +): boolean {
I vaguely remember eslint complaining about this but I removed it and it's not complaining now

2025-01-08 05:23 UTC, Bilb requested changes

2025-01-08 05:23 UTC, Bilb commented on run/test/specs/utils/check_colour.ts
> +  const isSameColor: boolean = colors(rgb1, rgb2);
no need for that `: boolean` here

2025-01-08 05:23 UTC, Bilb commented on run/test/specs/utils/check_colour.ts
> +  const isSameColor: boolean = colors(rgb1, rgb2);
it shouldn't be, as `colors()` is already typed correctly
```    export function colors(color1: Color, color2: Color): boolean;```

2025-01-08 05:23 UTC, Bilb commented on package.json
> +    "looks-same": "^9.0.1",
ok then

2025-01-10 04:14 UTC, Bilb approved these changes

2025-01-10 04:14 UTC, Bilb commented
LGTM

2025-01-13 02:33 UTC, burtonemily requested changes

2025-01-13 02:33 UTC, burtonemily commented on run/test/specs/check_avatar_color.spec.ts
> +  await device2.navigateBack();
These two navigateBack, should be grouped in a Promise.all

2025-01-13 02:33 UTC, burtonemily commented on run/test/specs/check_avatar_color.spec.ts
> +  }
Would be good to leave a comment as to why there is two different elements for the same thing here

2025-01-13 02:33 UTC, burtonemily commented on run/test/specs/check_avatar_color.spec.ts
> +  }
Also what element are you comparing in this test? Obviously the top left avatar in main screen but what are you comparing to on the other persons device? Probably should note that somewhere also

2025-01-13 02:33 UTC, burtonemily commented on run/test/specs/linked_device_avatar_color.spec.ts
> +  const device1PixelColor = await parseDataImage(device1Base64);
This could be turned into a separate function, maybe getElementColor or something?

2025-01-13 02:33 UTC, burtonemily commented on run/test/specs/locators/home.ts
> +      text: text,
Very nice

2025-01-15 06:08 UTC, Miki-Session commented on run/test/specs/linked_device_avatar_color.spec.ts
> +  const device1PixelColor = await parseDataImage(device1Base64);
I was anticipating this comment haha

2025-01-15 06:08 UTC, Miki-Session commented on run/test/specs/check_avatar_color.spec.ts
> +  }
Wrote a bit of an explanation for the difference in locators uses

2025-01-15 06:08 UTC, Miki-Session commented on run/test/specs/check_avatar_color.spec.ts
> +  await device2.navigateBack();
easy done

2025-01-17 00:17 UTC, burtonemily approved these changes
Looks good to me, nicely done

2025-01-17 00:18 UTC, merged